[[Xorg_libxshmfence]]
arch = "aarch64"
git-tree-sha1 = "e29d37876fe0c69fda1b4d5a80fee7652a739d12"
libc = "musl"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "407f759981c9cf15d003eb30f013da44bfff10e298d6521056097148290f8448"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.aarch64-linux-musl.tar.gz"
[[Xorg_libxshmfence]]
arch = "aarch64"
git-tree-sha1 = "0106a2750db652f31456b17375163bc1865573ff"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "449b3fafd4f1ebcb3a3707ac1ce21e68c394360683954b88f86684850254fca6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libxshmfence]]
arch = "x86_64"
git-tree-sha1 = "632430cc2f8908fd33e481b4621d7f3869c661d1"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "e064b8c6ffa0772b4f358593350d546cfa4c7d0b7c87487ca931fa56af6cde3f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libxshmfence]]
arch = "powerpc64le"
git-tree-sha1 = "ade8b499e9f3509f52bbc087a4350f62bbfd4af3"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "8b6c2fb6927fa1385742ec1c156b3279a2b045fd12990235860c0da207120086"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libxshmfence]]
arch = "x86_64"
git-tree-sha1 = "dfacc96d570e0cf42ed57f734f33048e3caf5f09"
os = "freebsd"

    [[Xorg_libxshmfence.download]]
    sha256 = "41e9f8c2bbe1e630273dac85cb2c6a6648b0a38b220e1b9fc0505a6d264911fc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libxshmfence]]
arch = "i686"
git-tree-sha1 = "2de4542b243cf13ef50209e94053daff891d1516"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "eb24b0e6876ce73c5bbc38fe22610d66ea2a0a0baf1316af66701f75aaeaaac1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.i686-linux-gnu.tar.gz"
[[Xorg_libxshmfence]]
arch = "i686"
git-tree-sha1 = "d0e16dd55ae0c02a38fe874ff0443122cf76ed4c"
libc = "musl"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "2e74c2e92aa8ba24932f953fee3273162e6a8ceef29496f3caa7753d118b0ee6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.i686-linux-musl.tar.gz"
[[Xorg_libxshmfence]]
arch = "armv7l"
git-tree-sha1 = "80d22c968ea1caa63a420988b9d3bd41535af5bf"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "1f37e57f62a016e088fda92a441a4b8e0df994ce170f206a0a5ba0fd4cf15a28"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libxshmfence]]
arch = "x86_64"
git-tree-sha1 = "6e13dfa48dfcdb85223de1d0233171477c251f3f"
libc = "musl"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "f3c292d6a2d044aa200ea209996c77e6618b66a3408fe3bb67de33697c7ff12d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.x86_64-linux-musl.tar.gz"
[[Xorg_libxshmfence]]
arch = "armv7l"
git-tree-sha1 = "fb6ce1c21d490a53325752b21cdf983bf1a50a81"
libc = "musl"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "ec4407d63a5270897fa087927ca4e66d9ceec3a536d5d179ed911847874c0bf8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+1/Xorg_libxshmfence.v1.3.0.armv7l-linux-musleabihf.tar.gz"
