[[Xorg_libxshmfence]]
arch = "armv7l"
git-tree-sha1 = "469ca15e278d98a3c73a60c962c75bef6c145694"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "c77a2edf7fbc2884b7c58baee5f4744533788167372514430b9d44afb8b5979d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libxshmfence]]
arch = "i686"
git-tree-sha1 = "6cae7ede9ad8f6b8181dfb8ea135eaf8e59b774c"
libc = "musl"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "68d7a02e2194b1e0a805da380f1418285de10bb1625dd3e47797e68d4c527cb7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.i686-linux-musl.tar.gz"
[[Xorg_libxshmfence]]
arch = "aarch64"
git-tree-sha1 = "6a9575a8fc22fbc4fe39a5ba476bb8ae8de7a255"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "c75b3cb42569eaf3036acb39157f32af88603c141cc475107a356ed28d642e17"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libxshmfence]]
arch = "armv7l"
git-tree-sha1 = "87fee5bb3ae9f87a694e78643bcfa54dfedde9cc"
libc = "musl"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "f443eb30152fdf286b57f8bf68c8631f72be763c9879e06ed0f00dfba36161b9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libxshmfence]]
arch = "aarch64"
git-tree-sha1 = "f059ffbaa30c2202e5d881d1e83f588020b5caf1"
libc = "musl"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "3a65187e7a9b438997d68c1f43226e019b92fd44220c319db25497500bc23601"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.aarch64-linux-musl.tar.gz"
[[Xorg_libxshmfence]]
arch = "x86_64"
git-tree-sha1 = "246b4ef9fdafdb8f746ca25fba459fd4a90bcfc2"
os = "freebsd"

    [[Xorg_libxshmfence.download]]
    sha256 = "69fbf250f6f6f4016bdce3adc25ee6c0bf92b89af4a61911fabdc0d19ef62ba2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libxshmfence]]
arch = "i686"
git-tree-sha1 = "0db2f4ce4afc8a107b8cc81bbe4726baf48ca823"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "41dbfd69b6aac3f75e6b0793da2d4c8a9c2f0f09359d2d64bc3c441f3f68159a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.i686-linux-gnu.tar.gz"
[[Xorg_libxshmfence]]
arch = "x86_64"
git-tree-sha1 = "91d90f5f360e8d3a93fc0814cced3f06bdc7fb23"
libc = "musl"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "b8dcf00f226ae88712e4ad45b38e5c6b0c031fa111a26f2516cffffcebdf063b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.x86_64-linux-musl.tar.gz"
[[Xorg_libxshmfence]]
arch = "x86_64"
git-tree-sha1 = "4aaf5ffab8c59be212cf0b313203aa8168b28c8b"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "f113a3ad87b691f2c5873d489054f28a1df62205b7ba3de1cf2a83eb59afe8ad"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libxshmfence]]
arch = "powerpc64le"
git-tree-sha1 = "33ce42e74f4d49d5105ddcf1abde2f249646c858"
libc = "glibc"
os = "linux"

    [[Xorg_libxshmfence.download]]
    sha256 = "89e7ca9a57af4edbd665f7d3f048143c1db9f9df19629482a88b2987d0a41cf4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxshmfence_jll.jl/releases/download/Xorg_libxshmfence-v1.3.0+2/Xorg_libxshmfence.v1.3.0.powerpc64le-linux-gnu.tar.gz"
